spring:
  application:
    name: healthcare-records-api

  datasource:
    url: jdbc:postgresql://gondola.proxy.rlwy.net:44393/railway
    username: postgres
    password: VQibSsneAySyaHUvBUJdAtgmwQYenTKS

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
