spring:
  application:
    name: healthcare-records-api

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

#  datasource:
#    url: jdbc:postgresql://localhost:5432/healthcare_db
#    username: noushad
#    password: patel

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
